baseURL = "https://demo.gethugothemes.com/hargo/examplesite/"
disqusShortname = ""
languageCode = "en"
paginate = 10
summaryLength = "20"
theme = "hargo-hugo"
title = "Hargo | Hugo Ecommerce Site"
[[menu.footer]]
URL = "contact/"
name = "Contact"
weight = 5
[[menu.footer]]
URL = "terms-conditions/"
name = "Terms & Conditions"
weight = 4
[[menu.footer]]
URL = "faq/"
name = "FAQ"
weight = 3
[[menu.footer]]
URL = "blog/"
name = "Blog"
weight = 2
[[menu.footer]]
URL = "products/"
name = "Services"
weight = 1
[[menu.main]]
URL = "contact/"
name = "Contact"
weight = 4
[[menu.main]]
URL = "faq/"
name = "FAQ"
weight = 3
[[menu.main]]
URL = "blog/"
name = "Blog"
weight = 2
[[menu.main]]
URL = "products/"
name = "Services"
weight = 1
[params]
author = "Themefisher"
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
currencySymbol = "$"
description = "This is meta description"
email = "demo@email.com"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = ""
home = "Home"
location = "Dhaka, Bangladedsh"
logo = "images/logo.png"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
mobile = "0124857985320"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
[params.contact]
formAction = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "811cf0927332bf51f2e12f84608594ac"
websiteID = "444334"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
